### ISSUE TITLE
How can I use the gpt4o model?

### ISSUE THREAD

**Issue by truki20** [xulihang/ImageTrans-docs_en#5]
I would like to use this model as it provides a smoother translation in my opinion.

**Comment by xulihang** [comment]
You can modify the model param from `gpt-3.5-turbo` to `gpt4o` in preferences.

In addition, please open your issues here: https://github.com/xulihang/ImageTrans-docs/issues/

**Comment by xulihang** [comment]
Updated in: https://github.com/xulihang/ImageTrans-docs/issues/678
